version: '3.8'
name : postgres_system
services:
  postgres_db:
    image: postgres:latest
    restart: always
    container_name: PostgresCont
    environment:
      - POSTGRES_USER=uzair
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=mydatabase
    ports:
      - '5433:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=uzairahmedwyne@hotmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    depends_on:
      - postgres_db
volumes:
  postgres_db:
    driver: local
networks:
  default:
    driver: bridge